gamebeater/gamebeater/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include('django.contrib.auth.urls')),
	url(r'^games/', include('games.urls')),
	url(r'^$', TemplateView.as_view(template_name='home.html'), name="home"),
	url(r'^profiles/', include('profiles.urls'))
]

gamebeater/games/urls.py
from django.conf.urls import url

from . import views

app_name = 'games'
urlpatterns = [
	# ex: /games/
	url(r'^$', views.GameIndexView.as_view(), name='games')
]

gamebeater/profiles/urls.py
from django.conf.urls import url

from . import views
from .views import DashboardView, CompletionStatusUpdateView, AddGamesView, GameOwnershipCreationView, GameOwnershipUpdateView, GoalDashboardView, CreateGoalView, GoalCompletionStatusUpdateView, GameOwnershipDeletionView, GoalDeletionView, GoalUpdateView
import pdb

app_name = 'profiles'
urlpatterns = [
	# ex: /profiles/register/
	url(r'^register/$', views.register, name='register'),
	# ex: /profiles/dashboard/
	url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),
	# ex: /profiles/gameownerships/1/completion_status
	url(r'^gameownerships/(?P<pk>[0-9]+)/completion_status/$', CompletionStatusUpdateView.as_view(), name='completion_status_update'),
    # ex: /profiles/add_games/
    url(r'^add_games/$', AddGamesView.as_view(), name='add_games'),
    # ex: /profiles/gameownerships/
    url(r'^gameownerships/$', GameOwnershipCreationView.as_view(), name='create_ownership'),
    # ex: /profiles/gameownerships/1/
    url(r'^gameownerships/(?P<pk>[0-9]+)/$', GameOwnershipUpdateView.as_view(), name='update_ownership'),
    # ex: /profiles/gameownerships/1/delete/
    url(r'^gameownerships/(?P<pk>[0-9]+)/delete/$', GameOwnershipDeletionView.as_view(), name='delete_ownership'),
    # ex: /profiles/gameownerships/1/goals
    url(r'^gameownerships/(?P<pk>[0-9]+)/goals/$', GoalDashboardView.as_view(), name='goal_dashboard'),
    # ex: /profiles/gameownerships/1/add_goals
    url(r'^goals/$', CreateGoalView.as_view(), name='add_goals'),
    # ex: /profiles/goals/1/
    url(r'^goals/(?P<pk>[0-9]+)/$', GoalUpdateView.as_view(), name='update_goal'),
    # ex: /profiles/goals/1/completion_status
    url(r'^goals/(?P<pk>[0-9]+)/completion_status$', GoalCompletionStatusUpdateView.as_view(), name='completion_status_update_goal'),
    # ex: /profiles/goals/1/delete/
    url(r'^goals/(?P<pk>[0-9]+)/delete/$', GoalDeletionView.as_view(), name='delete_goal')
]

gamebeater/profiles/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

from games.models import Game, Platform
from .statuses import CompletionStatus, OwnershipStatus, ObjectsByStatus

class GamebeaterProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL
    )
    games = models.ManyToManyField(
        Game,
        through='GameOwnership'
    )

    def get_gameownerships_by_completion(self, completion_status):
        return self.gameownership_set.filter(completion_status=completion_status)

    def get_unaffiliated_games(self):
        return Game.objects.all().exclude(pk__in=self.games.all().values('pk'))

    def __unicode__(self):
        return self.user.username

class GameOwnership(models.Model):
    owner = models.ForeignKey(
        GamebeaterProfile,
        on_delete=models.CASCADE
    )
    game = models.ForeignKey(
        Game,
        on_delete=models.CASCADE
    )
    platform = models.ForeignKey(
        Platform,
        on_delete=models.CASCADE
    )
    ownership_status = models.CharField(
        max_length=1,
        choices=OwnershipStatus.CHOICES,
        default=OwnershipStatus.WANTS
    )
    completion_status = models.CharField(
        max_length=1,
        choices=CompletionStatus.CHOICES,
        default=CompletionStatus.NOT_STARTED
    )

    def get_goals_by_completion(self, completion_status):
        return self.goal_set.filter(status=completion_status)

    def __unicode__(self):
        return self.owner.user.username + " => " + self.game.title

class Goal(models.Model):
    ownership = models.ForeignKey(GameOwnership)

    text = models.CharField(
        max_length=400
    )
    start_time = models.DateTimeField(
        default=timezone.now,
        blank=True,
        null=True
    )
    complete_time = models.DateTimeField(
        default=None,
        blank=True,
        null=True
    )
    status = models.CharField(
        max_length=1,
        choices=CompletionStatus.CHOICES,
        default=CompletionStatus.NOT_STARTED
    )

    def get_goal_dashboard_url(self):
        return reverse('profiles:goal_dashboard', kwargs={'pk': self.ownership.pk})

    def get_absolute_url(self):
        return reverse('profiles:update_goal', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.text

gamebeater/profiles/forms.py
from django import forms
from django.contrib.auth.models import User

from .statuses import CompletionStatus 
from .models import GameOwnership, Goal

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	
	class Meta:
		model = User
		fields = ('username', 'email', 'password')

class CompletionStatusUpdateForm(forms.ModelForm):

	class Meta:
		model = GameOwnership
		fields = ('completion_status',)

class GameOwnershipForm(forms.ModelForm):

    class Meta:
        model = GameOwnership
        fields = ('owner', 'game', 'platform', 'ownership_status', 'completion_status')
        widgets = {'owner': forms.HiddenInput(), 'game': forms.HiddenInput}

class GameOwnershipUpdateForm(forms.ModelForm):

    class Meta:
        model = GameOwnership
        fields = ('platform', 'ownership_status', 'completion_status')

class GoalForm(forms.ModelForm):

    class Meta:
        model = Goal 
        fields = ('ownership', 'text', 'start_time', 'complete_time', 'status')
        widgets = {'ownership': forms.HiddenInput()}

class GoalCompletionStatusUpdateForm(forms.ModelForm):

	class Meta:
		model = Goal
		fields = ('status',)

gamebeater/profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, UpdateView, CreateView, ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http import Http404

from .forms import UserForm, CompletionStatusUpdateForm, GameOwnershipForm, GameOwnershipUpdateForm, GoalForm, GoalCompletionStatusUpdateForm
from .models import GamebeaterProfile, GameOwnership, Goal
from .statuses import get_all_objects_by_status, CompletionStatus

import sys

class DashboardView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        # TODO: add default values to forms
        # Handles display of Gamebeater Profile
        profile_pk = request.user.gamebeaterprofile.pk
        gamebeaterprofile = get_object_or_404(GamebeaterProfile, pk=profile_pk)
        gameownerships_by_completion_status_list = get_all_objects_by_status(gamebeaterprofile.games, CompletionStatus, gamebeaterprofile.get_gameownerships_by_completion)
        return render(
            request,
            'profiles/dashboard.html',
            {
                "gamebeaterprofile": gamebeaterprofile,
                "gameownerships_by_completion_status_list": gameownerships_by_completion_status_list,
                "completion_status_update_form": CompletionStatusUpdateForm
            }
        )

class AddGamesView(LoginRequiredMixin, ListView):
    template_name = 'profiles/add_games.html'
    context_object_name = 'add_game_forms'

    def get_queryset(self):
        unaffiliated_games = self.request.user.gamebeaterprofile.get_unaffiliated_games()
        ownership_list = []
        for game in unaffiliated_games:
            ownership = GameOwnershipForm(
                {"game": game, "owner": self.request.user.gamebeaterprofile}
            )
            ownership.fields['platform'].queryset = ownership.data['game'].platforms
            ownership_list.append(ownership)
        return tuple(ownership_list)

class PreventGetMixin():
    """
    This mixin allows views to always refuse get requests. This is useful
    when a view should only process a POST and not display a form.
    """
    def get(self, request, *args, **kwargs):
        raise Http404

class GameOwnershipCreationView(LoginRequiredMixin, PreventGetMixin, CreateView):
    model = GameOwnership
    form_class = GameOwnershipForm

    success_url = reverse_lazy("profiles:add_games")

class GameOwnershipUpdateView(LoginRequiredMixin, UpdateView):
    model = GameOwnership
    form_class = GameOwnershipUpdateForm
    context_object_name = 'ownership_object'
    template_name = 'profiles/gameownership_update.html'

    success_url = reverse_lazy("profiles:dashboard")

    def get(self, request, *args, **kwargs):
        context_object = self.get_object()
        update_form = GameOwnershipUpdateForm(instance=context_object)
        update_form.fields['platform'].queryset = context_object.game.platforms
        return render(
            request,
            'profiles/gameownership_update.html',
            {
                "update_form": update_form,
                self.context_object_name: context_object
            }
        )

class GameOwnershipDeletionView(LoginRequiredMixin, DeleteView):
    model = GameOwnership
    success_url = reverse_lazy('profiles:dashboard')

class CompletionStatusUpdateView(LoginRequiredMixin, PreventGetMixin, UpdateView):
    model = GameOwnership
    form_class = CompletionStatusUpdateForm

    success_url = reverse_lazy("profiles:dashboard")

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            gamebeater_profile = GamebeaterProfile(user=user)
            gamebeater_profile.save()

            registered = True

        else:
            print user_form.errors
    else:
        user_form = UserForm()

    return render(
        request,
        'profiles/register.html',
        {'user_form': user_form, 'registered': registered}
    )

# Goal Views

class RedirectGoalDashboardMixin():
    """
    This mixin allows goal views to redirect to the goal dashboard instead
    of the game ownership dashboard
    """
    def get_success_url(self):
        try:
            url = self.object.get_goal_dashboard_url()
        except AttributeError:
            raise ImproperlyConfigured(
                "No URL to redirect to. define a get_goal_dashboard method on the Model"
            )
        return url

class GoalDashboardView(LoginRequiredMixin, UpdateView):
    model = GameOwnership
    form_class = GoalCompletionStatusUpdateForm
    goal_creation_form = GoalForm
    context_object_name = 'ownership_object'
    template_name = 'profiles/goal_dashboard.html'

    #success_url = reverse_lazy("profiles:goal_dashboard", args=[self.kwargs.get(self.pk_url_kwarg)])

    def get(self, request, *args, **kwargs):
        profile_pk = request.user.gamebeaterprofile.pk
        gamebeaterprofile = get_object_or_404(GamebeaterProfile, pk=profile_pk)

        # We have to check that the profile exists before you get the object
        # this could be messed up
        # TODO: change routes to work properly with the profile
        context_object = self.get_object()
        goal_form = self.goal_creation_form(
            {"ownership": context_object.pk}
        )
        goals_by_completion_status_list = get_all_objects_by_status(context_object.goal_set, CompletionStatus, context_object.get_goals_by_completion)
        return render(
            request,
            self.template_name,
            {
                "goal_form": self.form_class,
                self.context_object_name: context_object,
                "goals_by_completion_status_list": goals_by_completion_status_list,
                "goal_creation_form": goal_form
            }
        )

class CreateGoalView(LoginRequiredMixin, PreventGetMixin, RedirectGoalDashboardMixin, CreateView):
    model = GameOwnership
    form_class = GoalForm
    
class GoalUpdateView(LoginRequiredMixin, UpdateView):
    model = Goal
    form_class = GoalForm
    context_object_name = 'goal_object'
    template_name = 'profiles/goal_update.html'

class GoalDeletionView(LoginRequiredMixin, RedirectGoalDashboardMixin, DeleteView):
    model = Goal

class GoalCompletionStatusUpdateView(LoginRequiredMixin, PreventGetMixin, RedirectGoalDashboardMixin, UpdateView):
    model = Goal
    form_class = GoalCompletionStatusUpdateForm

gamebeater/templates/profiles/add_games.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Gamebeater | Add Games{% endblock %}

{% block navbar %}
<!-- Nav bar section -->
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'profiles:dashboard' %}">Gamebeater</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li><a href="{% url 'profiles:dashboard' %}">Dashboard</a></li>
				<li class="active"><a href="">Add Games</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#user"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ request.user.username }}</a></li>
				<li><a href="{% url 'logout' %}">Logout</a></li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>
{% endblock %}

{% block content %}
<ol class="breadcrumb gamebeater-breadcrumb text-muted">
	<li><i>Add Games</i></li>
</ol>

<h1>Add Games</h1>

<div class="row">
    {% for add_game_form in add_game_forms %}
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>{{ add_game_form.data.game.title }}</h2>
            </div>
            <div class="panel-body">
                <form id="add_game_form" method="post" action="{% url 'profiles:create_ownership' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ add_game_form.non_field_errors }}
                    <label for="{{ add_game_form.owner.id_for_label }}" class="control-label">
                    </label>
                    {{ add_game_form.owner|add_class:"form-control" }}
                    <label for="{{ add_game_form.game.id_for_label }}" class="control-label">
                    </label>
                    {{ add_game_form.game|add_class:"form-control" }}
                    <div class="form-group">
                        {{ add_game_form.platform.errors }}
                        <label for="{{ add_game_form.platform.id_for_label }}" class="control-label">
                            Platform:
                        </label>
                        {{ add_game_form.platform|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        {{ add_game_form.ownership_status.errors }}
                        <label for="{{ add_game_form.ownership_status.id_for_label }}" class="control-label">
                            Ownership Status:
                        </label>
                        {{ add_game_form.ownership_status|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        {{ add_game_form.completion_status.errors }}
                        <label for="{{ add_game_form.completion_status.id_for_label }}" class="control-label">
                            Completion Status:
                        </label>
                        {{ add_game_form.completion_status|add_class:"form-control" }}
                    </div>
                    <div class="gamebeater-centeredBtn">
                        <button type="submit" class="btn btn-default">
                            Add Game
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

gamebeater/templates/profiles/dashboard.html
{% extends "base.html" %}

{% load status_list_filters %}
{% load widget_tweaks %}

{% block title %}Gamebeater | Dashboard{% endblock %}

{% block navbar %}
<!-- Nav bar section -->
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'profiles:dashboard' %}">Gamebeater</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Dashboard</a></li>
				<li><a href="{% url 'profiles:add_games' %}">Add Games</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#user"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ request.user.username }}</a></li>
				<li><a href="{% url 'logout' %}">Logout</a></li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>
{% endblock %}

{% block content %}
<ol class="breadcrumb text-muted gamebeater-breadcrumb">
	<li><i>Dashboard</i></li>
</ol>

<h1>Statistics</h1>

<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading" role="button" data-toggle="collapse"
			data-target="#completionStatsBox" aria-expanded="false" aria-controls="completionStatsBox">
				<h2 class="panel-title">
					Completion Statistics
					<span class="pull-right">
						<div class="progress gamebeater-statbox-progress">			
							{% for gameownerships_by_completion_status in gameownerships_by_completion_status_list %}
							<div class="progress-bar {% cycle 'progress-bar-danger' 'progress-bar-striped' 'progress-bar-warning' 'progress-bar-striped progress-bar-success' %}" role="progressbar" aria-valuenow="{{ gameownerships_by_completion_status.status_percentage }}" 
							aria-valuemin="0" aria-valuemax="100" style="width:{{ gameownerships_by_completion_status.status_percentage }}%">
								<span class="sr-only">{{ gameownerships_by_completion_status.status_percentage }}% {{ gameownerships_by_completion_status.status }}</span>
							</div>
							{% endfor %}
						</div>
					</span>
				</h2> 							
			</div>
			<div id="completionStatsBox" class="panel-collapse collapse">
				<!-- gamebeater-statpanel-->
				<ul class="panel-body list-group">
					{% for gameownerships_by_completion_status in gameownerships_by_completion_status_list %}
					<li class="list-group-item">
						{{ gameownerships_by_completion_status.status }}: {{ gameownerships_by_completion_status.status_percentage }}%
						<span class="pull-right">
							<div class="progress gamebeater-statbox-progress">
								<div class="progress-bar gamebeater-statbox-invisibleProgressBar" role="progressbar" style="width:{{ gameownerships_by_completion_status_list|previous_status_percentage:forloop.counter0 }}%">
								</div>
								<div class="progress-bar {% cycle 'progress-bar-danger' 'progress-bar-striped' 'progress-bar-warning' 'progress-bar-striped progress-bar-success' %}" role="progress-bar" aria-valuenow="{{ gameownerships_by_completion_status.status_percentage }}"
								aria-valuemin="0" aria-maxvalue="100" style="width:{{ gameownerships_by_completion_status.status_percentage }}%;">
									<span class="sr-only">{{ gameownerships_by_completion_status.status_percentage }}% {{ gameownerships_by_completion_status.status }}</span>
								</div>
							</div>
						</span>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>

<h1>Games</h1>

<div class="row">
	{% for gameownerships_by_completion_status in gameownerships_by_completion_status_list %}
	<div class="col-md-3">
		<div class="panel {% cycle 'panel-danger' 'panel-primary' 'panel-warning' 'panel-success' %}">
			<div class="panel-heading" role="button" data-toggle="collapse"
			data-target="#{{ gameownerships_by_completion_status.status|slugify }}Panel" aria-expanded="false" aria-controls="{{ gameownerships_by_completion_status.status|slugify }}Panel">
				<h2 class="gamebeater-completionPanel-panelHeader">{{ gameownerships_by_completion_status.status }} <span class="badge">{{ gameownerships_by_completion_status.object_list.count }}</span></h2>
			</div>
			<div id="{{ gameownerships_by_completion_status.status|slugify }}Panel" class="panel-body panel-collapse collapse in">
				{% for gameownership in gameownerships_by_completion_status.object_list %}
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3>
							<a href="{% url 'profiles:update_ownership' gameownership.pk %}">{{ gameownership.game.title }}</a>
							<span class="pull-right">
								<form id="completion_form" method="post" action="{% url 'profiles:delete_ownership' gameownership.pk %}" enctype="multipart/form-data">
									{% csrf_token %}
									<div class="form-group">
										<button class="btn btn-default" type="submit" name="submit">
											<span class="glyphicon glyphicon-remove"></span>
										</button>
									</div>
								</form>
							</span>
						</h3>
					</div>
					<div class="panel-body">
						<div class="btn-group btn-group-justified gamebeater-completionPanel-goalBtn">
							<a class="btn btn-default" href="{% url 'profiles:goal_dashboard' gameownership.pk %}">Goals <span class="badge">{{ gameownership.goal_set.count }}</span></a>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading gamebeater-centeredBtn" class="panel-heading" role="button" data-toggle="collapse"
							data-target="#{{ gameownership.game.title|slugify }}Genres" aria-expanded="false" aria-controls="{{ gameownership.game.title|slugify }}Genres">
								Genres <span class="badge">{{ gameownership.game.genres.all.count }}</span>
							</div>
							<div id="{{ gameownership.game.title|slugify }}Genres" class="panel-collapse collapse">
								<ul class="panel-body list-group">
									{% for genre in gameownership.game.genres.all %}
									<li class="list-group-item">{{ genre.name }}</li>
									{% endfor %}
								</ul>
							</div>
						</div>
						<form id="completion_form" method="post" action="{% url 'profiles:completion_status_update' gameownership.pk %}" enctype="multipart/form-data">
							{% csrf_token %}

							{{ completion_status_update_form.non_field_errors }}
							<div class="form-group">
								{{ completion_status_update_form.completion_status.errors }}
								<label class="control-label" for="{{ completion_status_update_form.completion_status.id_for_label }}">Completion Status:</label>
								{{ completion_status_update_form.completion_status|add_class:"form-control gamebeater-option"}}
							</div>

							<div class="gamebeater-centeredBtn">
								<button class="btn btn-default" type="submit" name="submit">
									Change Status
								</button>
							</div>
						</form>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

gamebeater/templates/profiles/gameownership_update.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Gamebeater | Update Game{% endblock %}

{% block navbar %}
<!-- Nav bar section -->
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'profiles:dashboard' %}">Gamebeater</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li><a href="{% url 'profiles:dashboard' %}">Dashboard</a></li>
				<li><a href="{% url 'profiles:add_games' %}">Add Games</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#user"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ request.user.username }}</a></li>
				<li><a href="{% url 'logout' %}">Logout</a></li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>
{% endblock %}

{% block content %}
<ol class="breadcrumb gamebeater-breadcrumb text-muted">
	<li><a href="{% url 'profiles:dashboard' %}"><i>Dashboard</i></a></li>
	<li><i>{{ ownership_object.game.title }}</i></li>
</ol>

<h1>{{ ownership_object.game.title }}</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
	
	{{ update_form.non_field_errors }}
	<div class="form-group">
		{{ update_form.platform.errors }}
		<label for="{{ update_form.platform.id_for_label }}" class="control-label">
			Platform:
		</label>
		{{ update_form.platform|add_class:"form-control" }}
	</div>
	<div class="form-group">
		{{ update_form.ownership_status.errors }}
		<label for="{{ update_form.ownership_status.id_for_label }}" class="control-label">
			Ownership Status:
		</label>
		{{ update_form.ownership_status|add_class:"form-control" }}
	</div>
	<div class="form-group">
		{{ update_form.completion_status.errors }}
		<label for="{{ update_form.completion_status.id_for_label }}" class="control-label">
			Completion Status:
		</label>
		{{ update_form.completion_status|add_class:"form-control" }}
	</div>
	<div class="gamebeater-centeredBtn">
		<button type="submit" class="btn btn-default">
			Update Game
		</button>
	</div>
</form>
{% endblock %}

gamebeater/templates/profiles/register.html
{% extends "base.html" %}
{% block title %}Gamebeater | Register{% endblock %}
{% block content %}
<h1>Register your Gamebeater account</h1>

{% if registered %}
<strong>Thanks for signing up!</strong>
{% else %}
<strong>Sign up here!</strong>

<form id="user_form" method="post" action="{% url 'profiles:register' %}" enctype="multipart/form-data">
	{% csrf_token %}
	
	{{ user_form.as_p }}
	
	<input type="submit" name="submit" value="Register" />
</form>
{% endif %}

{% endblock %}